### ISSUE TITLE
🔄 teamdigitale/dpt-services-infra-tf-modules, teamdigitale/dpt-services-infra-tf-live, teamdigitale/devita-infra-tf-modules, teamdigitale/devita-infra-tf-live

### ISSUE THREAD

**Issue by developers-italia-droid** [italia/.github#197]
### The following repos were removed or archived
* [teamdigitale/dpt-services-infra-tf-modules](https://github.com/teamdigitale/dpt-services-infra-tf-modules)
* [teamdigitale/dpt-services-infra-tf-live](https://github.com/teamdigitale/dpt-services-infra-tf-live)
* [teamdigitale/devita-infra-tf-modules](https://github.com/teamdigitale/devita-infra-tf-modules)
* [teamdigitale/devita-infra-tf-live](https://github.com/teamdigitale/devita-infra-tf-live)

**Comment by bfabio** [comment]
Abbandono di Terraform, dopo aver considerato pro e contro

**Comment by LucaPrete** [comment]
☠️😢 quite a shame. RIP

**Comment by bfabio** [comment]
@LucaPrete I know, but the overhead of maintaining it got too big, the especially now that the infrastructure is shrinking quite a lot - we also consolidated everything in one k8s cluster.

Your precious work is not lost though, it's still as valuable as before as a reference.

**Comment by LucaPrete** [comment]
<3

Il giorno lun 13 feb 2023 alle ore 11:31 Fabio Bonelli <
***@***.***> ha scritto:
